### PR TITLE
Add explanation about menus.

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by davidmilligan** [comment]
This documentation is automatically generated from the source code: https://bitbucket.org/hudson/magic-lantern/branch/lua I will update it with something similar when I get a chance. There's actually a lot more general information like this that needs to be documented.

**Comment by skorokithakis** [comment]
Sure. I still haven't managed to get ml-lua running on the nightly build I downloaded for my camera, so I'll just leave it for now, hopefully some other build will get it working again.

**Comment by davidmilligan** [comment]
You have to build ML yourself from source, there are instructions on the forum. Hopefully it will be ready to be merged soon. Finishing up some of this documentation is most of the work.

**Comment by skorokithakis** [comment]
I saw the instructions, but I thought that the forum was out of date, since the `scripts` directory in my SD card already contained some Lua scripts, and was wondering why they wouldn't run. That's why I suggested having up-to-date instructions in the repo itself. I'll give it a shot, thanks.

**Pull request closed without merging**
